# Generated by hardware/generate.py firmware -- do not edit.
SRC += he_matrix.c

# Optional trackpad beside Y/H/N: Azoteq TPS65 under a 1 mm overlay (hardware/vgacorne/trackpad.py).
# Without a pad fitted, QMK gives up on it after one failed init at boot.
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx
